spring.application.name=SpringDataJpaDemo

spring.datasource.url=jdbc:postgresql://ep-snowy-pine-auv5l9wk-pooler.c-10.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_eT0GAlEhP6Oc&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_eT0GAlEhP6Oc

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true